name: Docker push in yandex cloud

on:
  push:
    branches: [ "trunk" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpbc6dfqke0h2ataotm
          CR_REPOSITORY: linkshorter
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Deploy COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@v2
        env:
          CR_REGISTRY: crpbc6dfqke0h2ataotm
          CR_REPOSITORY: linkshorter
          IMAGE_TAG: ${{ github.sha }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: b1ggriejpfppr7ui7grq
          vm-name: linkshorter
          vm-service-account-id: ajemmb0q6mmktng0pak9
          vm-cores: 2
          vm-memory: 2Gb
          vm-core-fraction: 20
          vm-subnet-id: e2lo6e5bj7cu83k3n4df
          user-data-path: './user-data.yaml'
          docker-compose-path: './docker-compose.yaml'
